/* 
**  mod_cpp4a.c -- Apache sample cpp4a module
**  [Autogenerated via ``apxs -n cpp4a -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_cpp4a.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /cpp4a in as follows:
**
**    #   httpd.conf
**    LoadModule cpp4a_module modules/mod_cpp4a.so
**    <Location /cpp4a>
**    SetHandler cpp4a
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /cpp4a and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/cpp4a 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_cpp4a.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int cpp4a_handler(request_rec *r)
{
    if (strcmp(r->handler, "cpp4a")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    //if (!r->header_only)
        ap_rputs("The sample page from mod_cpp4a.c\n", r);
    return OK;
}

static void cpp4a_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(cpp4a_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA cpp4a_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    cpp4a_register_hooks  /* register hooks                      */
};

